### PR TITLE
Make home page more minimal, tweak About page, move css overrides to this repo

### LINKED ISSUE #31: Go back to a minimal home page, use menu sections more.
Personally, I think that the text in the scroll-down section of the home page makes it too cluttered and repeats information that already is or could be in other sections of the website (namely, "About" and "News"). I propose that we go back to a minimal home page layout ([profile mode](https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/#profile-mode)) and keep the information posted in "News" and "About" sections.

Apart from aesthetics, this would make maintenance much easier, as it would use basic Hugo features, removing the need to tinker with the (fork of) Papermod template. There would be two ways to add new information:
- a single markdown file (with `layout: post` in front matter) placed in in `news/` will become a single news item; news items are aggregated in news page and can be viewed individually - see #30 
- a single markdown file (with `menu: main` and `weight: N`) will become a standalone page, included in the menu shown on top (Location, Schedule, Code of Conduct are like this already).

If there is a desire to keep some information available through the home page, we can consider using [regular](https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/#regular-mode-default-mode) or home-info modes, that would display news items (added as described above) rather than hard coded template content. If that is the case, please let me know, otherwise I will propose a PR with the minimalist solution.

Self-assigning because I want to propose a PR - but feel free to voice protests or suggestions here.

### PR DESCRIPTION
**Pull request by mslw**
This PR proposes going back to a minimalist home page, with only logo, title, social icons, buttons, and top menu (no announcement text on home page), closes #31 :

Screenshot from 2023-11-07 14-02-22

All information which got removed from the home page was already present in About and News sections of the website.

Buttons other than registration are also removed - everything is already accessible from the top menu. Conversely, (external) registration link is removed from the menu. This keeps one link for each target, and makes the home page look leaner (this change is one commit, can be reverted if unpopular).

The About page is slightly updated; while still 90% based on the call for contributions, IMHO it should work better on its own now.

Tweaks done previously to the fork of the theme are now done in this repo, using Hugo's way to [Customize a theme](https://gohugobrasil.netlify.app/themes/customizing/) in which files placed in project's folder take precedence over contents of `themes/<theme>` (which means I copied affected css files).

Altogether, I think this should both improve the feel of the website and make adding new content easier. See individual commit messages for descriptions, and try a local build to see rendered changes.

### CODE REVIEW

**Comment by mslw** [comment]
If, however, text on the home page is desired, it can be done using Papermod theme [home-info](https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/#home-info-mode) mode, which would display News cards on the main page (however, it allows limited ways of styling the home page, hence the less prominent subtitle):

Screenshot from 2023-11-07 13-31-02

This patch enables the look above:

``` patch
diff --git a/config.toml b/config.toml
index 0fb973d..362b4e1 100644
--- a/config.toml
+++ b/config.toml
@@ -16,25 +16,13 @@ theme = "PaperMod2"
     weight = 5
     
 [params]
-  [params.profileMode]
-    enabled = true
-    title = 'Technologies for distributed data management'
-    # subtitle = "Supported by DataLad and git-annex"
-    imageUrl = "pics/distribits_logo_a.svg"
-    imageTitle = "distribits_logo"
-    imageWidth = 800
-  [[params.profileMode.buttons]]
-    name = "🚀 Register"
-    url = 'https://cryptpad.fr/form/#/2/form/view/jnreOeG+ja0DXCESlqkgf6WRqz7vhMmxzROMyJL+q5g/'
-  [[params.profileMode.buttons]]
-    name = "💡 About"
-    url = "/about"
-  [[params.profileMode.buttons]]
-    name = "🔄 News"
-    url = "/news"
-
-  # repeat as many times as needed
-  # icon names -> grep icon_name themes/PaperMod/layouts/partials/svg.html
+  [params.homeInfoParams]
+    content = """\
+    ![Distribits 2024](/pics/distribits_logo_a.svg)\
+    **Technologies for distributed data management**\
+    """
+  # # repeat as many times as needed
+  # # icon names -> grep icon_name themes/PaperMod/layouts/partials/svg.html
   [[params.socialIcons]]
     name = "mastodon"
     url = "https://fosstodon.org/@distribits"

```

Personally, I prefer the more minimal look included in this PR - all content is accessible anyway through the top menu.

**Comment by adswa** [comment]
I like the minimalist overview as well

**Comment by mslw** [comment]
@jsheunis As a technical thing, I went for copying select css files over into this repo and patching them here (as hugo supports this kind of override), but TBF I don't think it is better or worse than working with a fork of the theme. I know you worked with the theme before. Do you have a preference, especially in terms of making it easy to spot and apply changes? If so, I am also happy to rebase the PR to work with submodule tweaks instead of css file copies.

**Comment by jsheunis** [comment]
I like these updates 👏  I vote for maintaining everything in this repo and not in the submodule. The initial reason for updating submodule content was because there was a request to have the "Call for participation" section on the main page. Now that the participation submission is finished and we have enough info in `about` and `news`, I like the idea of going for the minimal home page again.

**Review by jsheunis — APPROVED** [review]

**Pull request merged**
